DUMMY_PRODUCTS = [
    [
        {
            "id": 1,
            "title": "Luminous Silk Foundation",
            "price": 42,
            "description": "A lightweight liquid foundation that achieves a radiant, silky finish. Suitable for all skin types.",
        },
        {
            "id": 2,
            "title": "Velvet Matte Lipstick",
            "price": 35,
            "description": "Rich, full-coverage lipstick with a creamy matte finish. Long-lasting formula in a range of stunning shades.",
        },
        {
            "id": 3,
            "title": "Hydration Burst Face Cream",
            "price": 50,
            "description": "Intensely hydrating face cream that nourishes skin and locks in moisture for up to 24 hours.",
        },
        {
            "id": 4,
            "title": "Golden Glow Highlighter",
            "price": 28,
            "description": "A powder highlighter that gives skin a beautiful, natural-looking radiance. Perfect for all skin tones.",
        },
        {
            "id": 5,
            "title": "Soothing Eye Contour Cream",
            "price": 45,
            "description": "Gentle cream designed to reduce the appearance of fine lines and puffiness around the eyes.",
        },
        {
            "id": 6,
            "title": "Chic Summer Dress",
            "price": 99,
            "description": "Lightweight and breezy, perfect for summer outings. Comes in floral and solid colors.",
        },
        {
            "id": 7,
            "title": "Leather Tote Bag",
            "price": 150,
            "description": "Elegant and practical leather tote bag, spacious enough for all your essentials.",
        },
        {
            "id": 8,
            "title": "Classic Denim Jacket",
            "price": 75,
            "description": "A timeless piece that adds a cool edge to any outfit. Made from high-quality denim.",
        },
        {
            "id": 9,
            "title": "Silk Scarf",
            "price": 60,
            "description": "Add a touch of elegance to your wardrobe with this luxurious silk scarf. Available in various prints.",
        },
        {
            "id": 10,
            "title": "Minimalist Sneakers",
            "price": 110,
            "description": "Comfort meets style in these minimalist sneakers. Perfect for everyday wear.",
        },
    ],
    [
        {
            "id": 11,
            "title": "Exfoliating Sugar Scrub",
            "price": 30,
            "description": "Natural sugar scrub that gently exfoliates and moisturizes, leaving skin soft and smooth.",
        },
        {
            "id": 12,
            "title": "Volumizing Mascara",
            "price": 25,
            "description": "Clump-free mascara that delivers dramatic volume and length, for standout lashes.",
        },
        {
            "id": 13,
            "title": "Sunset Eyeshadow Palette",
            "price": 55,
            "description": "A palette of warm, sun-drenched hues. High-pigment shades for an endless array of looks.",
        },
        {
            "id": 14,
            "title": "Brightening Vitamin C Serum",
            "price": 60,
            "description": "Potent vitamin C serum that brightens, evens out skin tone, and reduces signs of aging.",
        },
        {
            "id": 15,
            "title": "Nourishing Lip Balm",
            "price": 10,
            "description": "Hydrating lip balm with a hint of color. Keeps lips soft and nourished throughout the day.",
        },
        {
            "id": 16,
            "title": "Refreshing Facial Toner",
            "price": 22,
            "description": "Alcohol-free toner that refreshes and balances the skin, preparing it for moisturizing.",
        },
        {
            "id": 17,
            "title": "Anti-Aging Night Cream",
            "price": 75,
            "description": "Rich night cream that works overnight to reduce wrinkles and rejuvenate the skin.",
        },
        {
            "id": 18,
            "title": "Mineral Setting Powder",
            "price": 32,
            "description": "Lightweight setting powder that provides a flawless, long-lasting finish.",
        },
        {
            "id": 19,
            "title": "Charcoal Detox Mask",
            "price": 40,
            "description": "Deep cleansing mask that removes impurities and minimizes the appearance of pores.",
        },
        {
            "id": 20,
            "title": "Hydrating Body Lotion",
            "price": 18,
            "description": "Moisturizing body lotion with a light, refreshing scent. Absorbs quickly without a greasy residue.",
        },
    ],
    [
        {
            "id": 21,
            "title": "Eco-Friendly Cotton Tee",
            "price": 35,
            "description": "Soft, sustainable cotton tee in a variety of colors. Perfect for everyday wear.",
        },
        {
            "id": 22,
            "title": "Vintage Leather Belt",
            "price": 45,
            "description": "High-quality vintage leather belt that adds a rustic touch to any outfit.",
        },
        {
            "id": 23,
            "title": "Bohemian Maxi Dress",
            "price": 120,
            "description": "Flowy and ethereal, this maxi dress is perfect for any occasion, from beach to dinner.",
        },
        {
            "id": 24,
            "title": "Waterproof Hiking Boots",
            "price": 130,
            "description": "Durable and waterproof hiking boots designed for ultimate comfort and traction on any terrain.",
        },
        {
            "id": 25,
            "title": "Slim Fit Jeans",
            "price": 90,
            "description": "Versatile slim fit jeans made from stretch denim for comfort and style.",
        },
        {
            "id": 26,
            "title": "Athletic Sports Bra",
            "price": 50,
            "description": "Supportive and comfortable sports bra, perfect for high-impact activities.",
        },
        {
            "id": 27,
            "title": "Designer Sunglasses",
            "price": 150,
            "description": "Stylish sunglasses offering superior UV protection. A blend of fashion and function.",
        },
        {
            "id": 28,
            "title": "Cashmere Scarf",
            "price": 100,
            "description": "Luxurious cashmere scarf, adding a touch of elegance and warmth to any outfit.",
        },
        {
            "id": 29,
            "title": "Faux Leather Jacket",
            "price": 110,
            "description": "Trendy and ethical faux leather jacket that pairs well with any outfit.",
        },
        {
            "id": 30,
            "title": "Elegant Woolen Blazer",
            "price": 140,
            "description": "Chic woolen blazer that combines sophistication with warmth. Perfect for formal and casual occasions alike.",
        },
    ],
]
